# Generated by Django 5.1.3 on 2025-05-25 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_userprofile_last_date_of_donation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('patient_type', models.CharField(choices=[('Child', 'Child'), ('Adult', 'Adult'), ('Elderly', 'Elderly'), ('Pregnant Woman', 'Pregnant Woman'), ('Accident Victim', 'Accident Victim'), ('Surgery Patient', 'Surgery Patient')], max_length=20)),
                ('hospital_name', models.CharField(max_length=100)),
                ('hospital_address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('urgency', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Critical', 'Critical')], default='Normal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Donation_req',
        ),
    ]
