# Generated by Django 5.1.3 on 2025-05-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_alter_donor_blood_group_alter_donor_city_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_date_of_donation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
